apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nchc-test
  labels:
    name: nchc-test
spec:
  selector:
    matchLabels:
      name: nchc-test
  template:
    metadata:
      labels:
        name: nchc-test
    spec:
      containers:
      - name: nchc-test
        image: theresaliao/nchc-test-gpu:0.67
        command: [ "/bin/bash", "-c", "sleep 2147483647", "python train.py -t nfbCCTV-N3-S-275.5-M -s --address_ip 0.0.0.0 --serve_port 80"]
        ports:
        - containerPort: 80
        - containerPort: 81
        - containerPort: 82
        - containerPort: 83
        - containerPort: 84
        - containerPort: 85
        - containerPort: 86
        - containerPort: 87
        - containerPort: 88
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: weight
          mountPath: /usr/src/app/weights/
      volumes:
      - name: weight
        hostPath:
          path: /home/weights/
---
apiVersion: v1
kind: Service
metadata:
  name: nchc-test
  labels:
    name: nchc-test
spec:
  ports:
  - name: camara-0
    port: 80
    nodePort: 30010
  - name: camara-1
    port: 81
    nodePort: 30011
  - name: camara-2
    port: 82
    nodePort: 30012
  - name: camara-3
    port: 83
    nodePort: 30013
  - name: camara-4
    port: 84
    nodePort: 30014
  - name: camara-5
    port: 85
    nodePort: 30015
  - name: camara-6
    port: 86
    nodePort: 30016
  - name: camara-7
    port: 87
    nodePort: 30017
  - name: camara-8
    port: 88
    nodePort: 30018
  selector:
    name: nchc-test
  type: NodePort
