apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nchc-test
  namespace: kube-system
  labels:
    name: nchc-test
spec:
  selector:
    matchLabels:
      name: nchc-test
  template:
    metadata:
      labels:
        name: nchc-test
    spec:
      containers:
      - name: nchc-test
        image: theresaliao/nchc-test-gpu:0.64
        volumeMounts:
        - name: weight
          mountPath: /usr/src/app/weights
      terminationGracePeriodSeconds: 0
      volumes:
      - name: weight
        hostPath:
          path: /home/src/weights
